### ISSUE TITLE
Test Request of E Learn Platform

### ISSUE THREAD

**Issue by bariskarapinar** [bariskarapinar/bounswe573-2022#31]

**Comment by gamebit34** [comment]
Test done. No bugs.

**Comment by gamebit34** [comment]
![Screen Shot 2022-05-17 at 15 43 08](https://user-images.github
![Screen Shot 2022-05-17 at 15 35 09](https://user-images.githubusercontent.com/30619162/168833655-e197c5d2-6982-49b8-80f2-86f67144312f.png)
![Screen Shot 2022-05-17 at 15 36 26](https://user-images.githubusercontent.com/30619162/168833663-2de45255-e3fb-435a-b7e7-7ef33ad5b24c.png)
![Screen Shot 2022-05-17 at 15 37 22](https://user-images.githubusercontent.com/30619162/168833667-05fe508e-4ef2-4799-878b-add1486dcf04.png)
![Screen Shot 2022-05-17 at 15 37 27](https://user-images.githubusercontent.com/30619162/168833672-43105916-e3c9-4e40-b20e-a0130fc79529.png)
![Screen Shot 2022-05-17 at 15 38 31](https://user-images.githubusercontent.com/30619162/168833678-9eea2f60-82c7-436e-9841-70f0d288883e.png)
![Screen Shot 2022-05-17 at 15 42 04](https://user-images.githubusercontent.com/30619162/168833684-74412fdb-b82d-4af1-a742-3a0fc3e6dfbc.png)
![Screen Shot 2022-05-17 at 15 42 12](https://user-images.githubusercontent.com/30619162/168833691-770913f8-e96c-422d-9216-ff98629c8c48.png)
usercontent.com/30619162/168833610-dbcc61db-9095-4ecb-8f45-23b764ff1894.png)
